import React from 'react';
import studioImage from '../../../public/assets/dailies-marketing-image-1.png'; import mossImage from '../../../public/assets/dailies-marketing-image-3.png'; import clayImage from '../../../public/assets/dailies-marketing-image-2.png';
const images = [studioImage, mossImage, clayImage]; const labels = { complete: 'Ready to review', failed: 'Needs attention', analyzing: 'Analysis in progress', scoring: 'Score in progress', querying_insights: 'Insight in progress', uploaded: 'Ready to analyze', uploading: 'Uploading', created: 'Created' };
export default function Dashboard({ user, projects, fixtureMode, onNewProject, onOpenProject, onBrowseProjects }) {
  const finished = projects.filter((p) => p.status === 'complete'); const latest = finished[0]?.report?.recommendation;
  return <main className="dashboard-main"><section className="dashboard-welcome"><div><p className="eyebrow">Creator desk {fixtureMode && <span className="demo-badge">Fixture mode</span>}</p><h1>Good afternoon, <em>{user.firstName}.</em></h1><p>{projects.length ? 'Your recent work is waiting.' : 'Bring in a cut to begin.'}</p></div><button className="button primary" onClick={onNewProject}>Start a project <span>↗</span></button></section>
    <section className="dashboard-grid"><article className="dashboard-focus"><div className="focus-top"><span className="eyebrow">Latest grounded signal</span><span className="focus-mark">✦</span></div><h2>{latest?.recommendationText || 'No retention recommendation yet.'}</h2><p>{latest?.observedEvidence || 'Complete a project after syncing YouTube Analytics to see creator-specific evidence.'}</p>{latest && <button className="text-button dashboard-link" onClick={() => onOpenProject(finished[0].projectId)}>Open the evidence <span>→</span></button>}</article><article className="dashboard-activity"><p className="eyebrow">Project activity</p><h2>What is waiting.</h2><div className="activity-list"><div><i className="activity-dot lavender" /><span><strong>{finished.length}</strong> ready to review</span></div><div><i className="activity-dot apricot" /><span><strong>{projects.filter((p) => ['analyzing','scoring','querying_insights'].includes(p.status)).length}</strong> in progress</span></div></div><button className="text-button dashboard-link" onClick={onBrowseProjects}>View every project <span>→</span></button></article></section>
    <section className="project-library"><div className="library-heading"><div><p className="eyebrow">Recent projects</p><h2>The work on your desk.</h2></div></div>{projects.length === 0 ? <p>No projects yet.</p> : <div className="project-card-grid">{projects.map((project, index) => <article className="project-card" key={project.projectId}><div className="project-card-image"><img src={images[index % images.length]} alt="" /><span className={`project-status ${project.status === 'complete' ? 'ready' : 'working'}`}>{labels[project.status] || project.status}</span></div><div className="project-card-body"><div><p className="project-updated">{new Date(project.updatedAt).toLocaleString()}</p><h3>{project.title}</h3><p>{project.outline || project.fileName}</p></div><dl><div><dt>{project.durationSeconds ? `${Math.round(project.durationSeconds)}s` : '—'}</dt><dd>rough cut</dd></div><div><dt>{project.report?.analysis?.scenes?.length || '—'}</dt><dd>scenes</dd></div></dl><div className="project-card-insight"><span>Next note</span><strong>{project.report?.recommendation?.recommendationText || project.statusMessage}</strong></div><button className="project-open" onClick={() => onOpenProject(project.projectId)}>View project <span>↗</span></button></div></article>)}</div>}</section></main>;
}
