import React, { useEffect, useState } from 'react';
import { api } from '../api.js';
import studioImage from '../../../public/assets/dailies-marketing-image-1.png'; import mossImage from '../../../public/assets/dailies-marketing-image-3.png'; import clayImage from '../../../public/assets/dailies-marketing-image-2.png';
const images = [studioImage, mossImage, clayImage]; const labels = { complete: 'Ready to review', failed: 'Needs attention', analyzing: 'Analysis in progress', scoring: 'Score in progress', querying_insights: 'Insight in progress', uploaded: 'Ready to analyze', uploading: 'Uploading', created: 'Created' };
const syncStageLabel = (stage) => String(stage || 'running').replaceAll('_', ' ');
export default function Dashboard({ user, projects, fixtureMode, onNewProject, onOpenProject, onBrowseProjects }) {
  const finished = projects.filter((p) => p.status === 'complete'); const latest = finished[0]?.report?.recommendation;
  const [youtube, setYoutube] = useState({ loading: true, configured: false, connected: false }); const [youtubeAction, setYoutubeAction] = useState(''); const [youtubeError, setYoutubeError] = useState('');
  useEffect(() => { let current = true; api.youtubeStatus().then((value) => current && setYoutube({ ...value, loading: false })).catch((error) => { if (current) { setYoutube((value) => ({ ...value, loading: false })); setYoutubeError(error.message); } }); return () => { current = false; }; }, []);
  useEffect(() => { if (youtube.syncState !== 'running') return undefined; const timer = window.setInterval(() => api.youtubeStatus().then((value) => { setYoutube({ ...value, loading: false }); if (value.syncState === 'failed') setYoutubeError(value.lastSyncError || 'YouTube sync failed.'); }).catch((error) => setYoutubeError(error.message)), 1500); return () => window.clearInterval(timer); }, [youtube.syncState]);
  const connectYouTube = async () => { setYoutubeAction('connect'); setYoutubeError(''); try { const { url } = await api.youtubeConnect(); window.location.assign(url); } catch (error) { setYoutubeError(error.message); setYoutubeAction(''); } };
  const syncYouTube = async () => { setYoutubeAction('sync'); setYoutubeError(''); try { await api.youtubeSync(); setYoutube({ ...(await api.youtubeStatus()), loading: false }); } catch (error) { setYoutubeError(error.message); } finally { setYoutubeAction(''); } };
  const disconnectYouTube = async () => { if (!window.confirm('Disconnect YouTube and remove the stored authorization? Your Dailies projects will remain available.')) return; setYoutubeAction('disconnect'); setYoutubeError(''); try { await api.youtubeDisconnect(); setYoutube({ configured: true, connected: false, loading: false }); } catch (error) { setYoutubeError(error.message); } finally { setYoutubeAction(''); } };
  return <main className="dashboard-main"><section className="dashboard-welcome"><div><p className="eyebrow">Creator desk {fixtureMode && <span className="demo-badge">Fixture mode</span>}</p><h1>Good afternoon, <em>{user.firstName}.</em></h1><p>{projects.length ? 'Your recent work is waiting.' : 'Bring in a cut to begin.'}</p></div><button className="button primary" onClick={onNewProject}>Start a project <span>↗</span></button></section>
    <section className="dashboard-grid"><article className="dashboard-focus"><div className="focus-top"><span className="eyebrow">Latest grounded signal</span><span className="focus-mark">✦</span></div><h2>{latest?.recommendationText || 'No retention recommendation yet.'}</h2><p>{latest?.observedEvidence || 'Complete a project after syncing YouTube Analytics to see creator-specific evidence.'}</p>{latest && <button className="text-button dashboard-link" onClick={() => onOpenProject(finished[0].projectId)}>Open the evidence <span>→</span></button>}</article><article className="dashboard-activity"><p className="eyebrow">Project activity</p><h2>What is waiting.</h2><div className="activity-list"><div><i className="activity-dot lavender" /><span><strong>{finished.length}</strong> ready to review</span></div><div><i className="activity-dot apricot" /><span><strong>{projects.filter((p) => ['analyzing','scoring','querying_insights'].includes(p.status)).length}</strong> in progress</span></div></div><button className="text-button dashboard-link" onClick={onBrowseProjects}>View every project <span>→</span></button></article></section>
    <section className="youtube-connection" aria-labelledby="youtube-heading"><div className="youtube-connection-copy"><p className="eyebrow">Optional creator history</p><h2 id="youtube-heading">YouTube Analytics</h2><p>{youtube.connected ? 'Connected read-only. Sync retention history when you want another source of editing evidence.' : 'Connect your channel to compare cuts with your own retention history—or skip this entirely. Analysis, editing, and rendering still work without it.'}</p>{youtube.connected && youtube.lastSyncedAt && <small>Last synchronized {new Date(youtube.lastSyncedAt).toLocaleString()}</small>}{youtubeError && <p className="youtube-error" role="alert">{youtubeError}</p>}{youtube.connected && youtube.syncActivity?.length > 0 && <div className="youtube-sync-activity" aria-live="polite"><div><span className="eyebrow">Sync activity</span><b className={youtube.syncState === 'running' ? 'is-running' : ''}>{youtube.syncState}</b></div>{youtube.syncRunId && <p className="youtube-sync-run"><span>{syncStageLabel(youtube.syncStage)}</span>{youtube.syncProgress && <strong>{youtube.syncProgress.current} / {youtube.syncProgress.total}</strong>}</p>}<ol>{youtube.syncActivity.slice(-8).map((event, index) => <li key={`${event.createdAt}-${index}`}><time>{new Date(event.createdAt).toLocaleTimeString()}</time><span>{event.message}</span></li>)}</ol></div>}</div><div className="youtube-actions">{youtube.loading ? <span>Checking connection…</span> : !youtube.configured ? <span>OAuth setup is not available in this deployment.</span> : youtube.connected ? <><button className="button secondary" disabled={Boolean(youtubeAction) || youtube.syncState === 'running'} onClick={syncYouTube}>{youtube.syncState === 'running' || youtubeAction === 'sync' ? 'Synchronizing…' : 'Sync analytics'}</button><button className="text-button" disabled={Boolean(youtubeAction) || youtube.syncState === 'running'} onClick={disconnectYouTube}>Disconnect</button></> : <><button className="button secondary" disabled={Boolean(youtubeAction)} onClick={connectYouTube}>{youtubeAction === 'connect' ? 'Opening Google…' : 'Connect YouTube'}</button><span>No connection required</span></>}</div></section>
    <section className="project-library"><div className="library-heading"><div><p className="eyebrow">Recent projects</p><h2>The work on your desk.</h2></div></div>{projects.length === 0 ? <p>No projects yet.</p> : <div className="project-card-grid">{projects.map((project, index) => <article className="project-card" key={project.projectId}><div className="project-card-image"><img src={images[index % images.length]} alt="" /><span className={`project-status ${project.status === 'complete' ? 'ready' : 'working'}`}>{labels[project.status] || project.status}</span></div><div className="project-card-body"><div><p className="project-updated">{new Date(project.updatedAt).toLocaleString()}</p><h3>{project.title}</h3><p>{project.outline || project.fileName}</p></div><dl><div><dt>{project.durationSeconds ? `${Math.round(project.durationSeconds)}s` : '—'}</dt><dd>rough cut</dd></div><div><dt>{project.report?.analysis?.scenes?.length || '—'}</dt><dd>scenes</dd></div></dl><div className="project-card-insight"><span>Next note</span><strong>{project.report?.recommendation?.recommendationText || project.statusMessage}</strong></div><button className="project-open" onClick={() => onOpenProject(project.projectId)}>View project <span>↗</span></button></div></article>)}</div>}</section></main>;
}
