import React, { useEffect, useRef, useState } from 'react';
import { api } from '../api';
import AssetDownloadLink from './AssetDownloadLink.jsx';

export default function SoundtrackCard({ projectId, soundtrack, brief, cues = [] }) {
  const renderedIds = new Set(soundtrack?.cues?.map((cue) => cue.id) || []);
  const legacy = Boolean(soundtrack?.asset && !soundtrack?.cues?.length);
  return <section className="soundtrack-card report-panel">
    <div className="section-heading">
      <div><p className="eyebrow">02 · Editorial audio</p><h2>Sound only where the moment earns it.</h2></div>
      <div className="section-actions">
        {soundtrack?.asset && <AssetDownloadLink projectId={projectId} asset={soundtrack.asset}>Download custom soundtrack</AssetDownloadLink>}
      </div>
    </div>
    <div className="soundtrack-body">
      <p className="generation-brief">{soundtrack?.rationale || 'Audio decisions follow the timestamped analysis.'}</p>
      {legacy && <div className="legacy-score"><div><strong>Legacy continuous soundtrack</strong><span>This completed report predates cue-based audio. A new analysis is required to replace it with intentional moments.</span></div><CueAudio projectId={projectId} cue={{ asset: soundtrack.asset }} /></div>}
      {!cues.length && !legacy && <div className="intentional-silence"><strong>No added audio recommended</strong><span>Clean dialogue and intentional silence remain untouched.</span></div>}
      <div className="audio-cue-list">{cues.map((cue) => {
        const generated = soundtrack?.cues?.find((item) => item.id === cue.id);
        return <article key={cue.id}>
          <div className="audio-cue-time"><strong>{format(cue.startSeconds)}–{format(cue.endSeconds)}</strong><span>{cue.type.replace('_', ' ')}</span></div>
          <div><strong>{cue.purpose}</strong><p>{cue.mood} · {Math.round(cue.energy * 100)}% energy · {cue.dialoguePolicy.replaceAll('_', ' ')}</p>{cue.visualCompanion && <small>Visual companion: {cue.visualCompanion}</small>}{generated?.visualAsset && <small>Generated by {generated.visualAsset.generationModel}</small>}</div>
          <div className="audio-cue-status">{renderedIds.has(cue.id) ? <CueAudio projectId={projectId} cue={generated} /> : cue.type === 'silence' ? <span>Preserved silence</span> : <span>No asset generated</span>}</div>
        </article>;
      })}</div>
      {soundtrack?.needed && <details className="score-brief"><summary>Music-generation direction</summary><div className="brief-grid"><div><span>Mood</span><strong>{brief.mood}</strong></div><div><span>Tempo</span><strong>{brief.tempo}</strong></div><div><span>Instrument</span><strong>{brief.instrumentation}</strong></div></div><p className="generation-brief">{brief.prompt}</p></details>}
    </div>
  </section>;
}

function CueAudio({ projectId, cue }) {
  const [url, setUrl] = useState(''); const [error, setError] = useState(''); const audio = useRef(null); const start = cue?.sourceStartSeconds || 0; const end = cue?.sourceEndSeconds;
  useEffect(() => { if (!cue?.asset?.id) return; api.assetUrl(projectId, cue.asset.id).then((value) => setUrl(value.url)).catch((e) => setError(e.message)); }, [projectId, cue?.asset?.id]);
  const position = () => { if (audio.current && (audio.current.currentTime < start || (end && audio.current.currentTime >= end))) audio.current.currentTime = start; };
  const stopAtSliceEnd = () => { if (audio.current && end && audio.current.currentTime >= end) { audio.current.pause(); audio.current.currentTime = start; } };
  return url ? <audio ref={audio} controls preload="metadata" src={url} onLoadedMetadata={position} onPlay={position} onTimeUpdate={stopAtSliceEnd}>Generated music cue</audio> : <span>{error || 'Loading cue…'}</span>;
}
const format = (seconds) => `${Math.floor(seconds / 60)}:${String(Math.round(seconds % 60)).padStart(2, '0')}`;
