import React from 'react';

const stages = ['Ingest', 'Analyze', 'Score', 'Insight', 'Edit', 'Render'];
export default function WorkflowStepper({ status, currentStage, events = [], activityError, creatorHistoryEnabled }) {
  const visibleStage = status === 'uploading' ? 0 : currentStage;
  const activity = compactEvents(events);
  return <section className="workflow-stepper" aria-label="Project processing progress">
    <div className="eyebrow-row"><span className="eyebrow">Reading your cut</span><span className="status-copy" aria-live="polite">{status === 'uploading' ? 'Uploading footage' : status === 'uploaded' ? 'Ready to start processing' : status === 'analyzing' ? 'Gemini analysis in progress' : status === 'scoring' ? 'Lyria generation in progress' : status === 'querying_insights' ? 'ClickHouse MCP query in progress' : status === 'waiting_for_service' ? 'Waiting for ClickHouse MCP — checkpoints preserved' : status === 'editing' ? 'Building the enhanced timeline' : status === 'rendering' ? 'Rendering the final cut' : 'Preparing workflow'}</span></div>
    <div className="workflow-body"><ol>{stages.map((stage, index) => { const skipped = stage === 'Insight' && creatorHistoryEnabled === false; return <li key={stage} className={`${index < visibleStage ? 'is-complete' : index === visibleStage ? 'is-current' : ''}${skipped ? ' is-skipped' : ''}`}><span>{skipped ? '—' : index < visibleStage ? '✓' : `0${index + 1}`}</span><strong>{stage}{skipped && <small>Skipped · YouTube not connected</small>}</strong></li>; })}</ol>
      <div className="pipeline-activity" aria-live="polite"><div className="activity-heading"><span className="eyebrow">Live activity</span><span className={`activity-state ${isLive(status) ? 'is-live' : ''}`}><i />{stateLabel(status)}</span></div>{activityError ? <p className="activity-error">Activity temporarily unavailable.</p> : activity.length ? <ul>{activity.map((event) => <li key={event.eventId}><time dateTime={event.createdAt}>{formatTime(event.createdAt)}</time><span>{eventLabel(event)}</span></li>)}</ul> : <p className="activity-empty">Waiting for the first pipeline event.</p>}</div>
    </div>
  </section>;
}
const isLive = (status) => ['analyzing', 'scoring', 'querying_insights', 'editing', 'rendering'].includes(status);
const stateLabel = (status) => isLive(status) ? 'Running' : status === 'waiting_for_service' ? 'Paused' : status === 'complete' ? 'Complete' : status === 'failed' ? 'Stopped' : 'Not started';
const compactEvents = (events) => { const latest = new Map(); events.forEach((event) => latest.set(`${event.type}|${event.stage}|${event.message || ''}`, event)); return [...latest.values()].sort((a, b) => a.createdAt.localeCompare(b.createdAt)).slice(-8); };
const formatTime = (value) => new Intl.DateTimeFormat([], { hour: 'numeric', minute: '2-digit', second: '2-digit' }).format(new Date(value));
const eventLabel = (event) => event.type === 'lease_claimed' ? 'Worker resumed the recorded pipeline.' : event.type === 'lease_recovered' ? 'Recovered an expired worker lease.' : event.type === 'checkpoint' ? event.message || `${event.stage} checkpoint saved.` : event.type === 'waiting_for_service' ? 'Paused at Insight — ClickHouse MCP configuration required.' : event.type === 'retry_scheduled' ? event.message || 'Transient failure; retry scheduled.' : event.type === 'completed' ? 'Final cut and report completed.' : event.type === 'failed' ? event.message || 'Pipeline stopped.' : event.type === 'submitted' || event.type === 'retry_submitted' ? event.message || 'Pipeline submitted.' : event.message || event.stage;
