import { GoogleGenAI } from '@google/genai';
import { analysisResultSchema, type AnalysisResult } from '@dailies/shared';

export type AnalysisInput = { projectId: string; videoUri: string; mimeType: string; durationSeconds: number; outline: string };
export async function analyzeVideo(input: AnalysisInput): Promise<AnalysisResult> {
  const ai = new GoogleGenAI({ vertexai: true, project: required('GCP_PROJECT_ID'), location: process.env.VERTEX_LOCATION || 'global' });
  const prompt = `Analyze this creator-owned rough cut. Project id: ${input.projectId}. Known duration: ${input.durationSeconds} seconds. Optional outline: ${input.outline || 'none'}.
Treat this as a rough assembly that may be up to 60 minutes, not a finished film. Judge it as a YouTube viewer deciding whether to keep watching, not as documentation whose clarity alone deserves a high score. Penalize static screens, weak hooks, uniform delivery, low visual variety, and long explanations. Identify precise edit opportunities including silence, repetition, tangents, low-information actions that can be accelerated, jokes, reveals, momentum changes, montages, emphasis worth preserving, visual/exposure issues, audible noise, and moments suited to an emoji, confetti, glow, or picture-frame overlay.
Return JSON with projectId, durationSeconds, timestamped scenes (id, startSeconds, endSeconds, summary, transcript, mood, energy 0-1, pacingFlags), soundtrackBrief (mood, tempo, instrumentation, prompt), an empty legacy soundtrackSegments array, audioCues, editingSignals, and a viewerScore from 0-100. Editing signals need precise start/end timestamps, type, confidence, detail, and suggestedAction. Score hook, pacing, clarity, visualQuality, audioQuality, total, and explain the baseline. Do not invent dialogue you cannot hear.
Audio is editorial, not wallpaper. Silence and clean dialogue are the default. Return audioCues only when a specific moment earns one. Music is appropriate for a montage, reveal, transition, emotional peak, momentum pickup, or fast-forward—not as a continuous bed. Keep total music coverage sparse, normally below 25% of runtime. A joke may receive a short laugh_track cue with a laugh emoji visualCompanion. Important feature reveals in otherwise dry demos should receive a pop or celebratory sting plus a concise visualCompanion such as wow_callout, new_feature, nice_payoff, or bubble_reveal. Pick the 2-6 strongest moments, space them apart, and do not decorate routine navigation. Never place laugh effects over serious speech. Every cue needs exact start/end seconds, type, purpose, mood, energy, gainDb, fadeInSeconds, fadeOutSeconds, dialoguePolicy, and visualCompanion. Use no_dialogue when possible, duck_under_dialogue only for essential speech, and replace_source_audio for fast-forward/montage sections. An empty audioCues array is correct when the video needs no added audio.`;
  const response = await ai.models.generateContent({ model: process.env.GEMINI_MODEL || 'gemini-3-flash-preview', contents: [{ role: 'user', parts: [{ fileData: { fileUri: input.videoUri, mimeType: input.mimeType } }, { text: prompt }] }], config: { responseMimeType: 'application/json', responseJsonSchema: analysisJsonSchema } });
  if (!response.text) throw new Error('Gemini returned no structured analysis');
  const parsed = analysisResultSchema.parse(normalizeAnalysisTimestamps(JSON.parse(response.text), input.durationSeconds));
  if (parsed.projectId !== input.projectId) throw new Error('Gemini project id mismatch');
  return parsed;
}

export function normalizeAnalysisTimestamps(value: any, durationSeconds: number) {
  const normalize = (item: any) => {
    let startSeconds = clamp(Number(item.startSeconds), 0, durationSeconds);
    let endSeconds = clamp(Number(item.endSeconds), 0, durationSeconds);
    if (endSeconds <= startSeconds) {
      if (startSeconds >= durationSeconds) startSeconds = Math.max(0, durationSeconds - .5);
      endSeconds = Math.min(durationSeconds, startSeconds + .5);
    }
    return { ...item, startSeconds, endSeconds };
  };
  return {
    ...value,
    durationSeconds,
    scenes: Array.isArray(value.scenes) ? value.scenes.map(normalize) : value.scenes,
    soundtrackSegments: Array.isArray(value.soundtrackSegments) ? value.soundtrackSegments.map(normalize) : value.soundtrackSegments,
    audioCues: Array.isArray(value.audioCues) ? value.audioCues.map(normalize) : value.audioCues,
    editingSignals: Array.isArray(value.editingSignals) ? value.editingSignals.map(normalize) : value.editingSignals,
  };
}

const clamp = (value: number, minimum: number, maximum: number) => Math.min(maximum, Math.max(minimum, Number.isFinite(value) ? value : minimum));
const required = (name: string) => { const value = process.env[name]; if (!value) throw new Error(`${name} is required`); return value; };
const scoreJsonSchema = { type: 'object', additionalProperties: false, required: ['hook', 'pacing', 'clarity', 'visualQuality', 'audioQuality', 'total', 'rationale'], properties: { hook: { type: 'number', minimum: 0, maximum: 100 }, pacing: { type: 'number', minimum: 0, maximum: 100 }, clarity: { type: 'number', minimum: 0, maximum: 100 }, visualQuality: { type: 'number', minimum: 0, maximum: 100 }, audioQuality: { type: 'number', minimum: 0, maximum: 100 }, total: { type: 'number', minimum: 0, maximum: 100 }, rationale: { type: 'string' } } };
const cueJsonSchema = { type: 'object', additionalProperties: false, required: ['id', 'startSeconds', 'endSeconds', 'type', 'purpose', 'mood', 'energy', 'gainDb', 'fadeInSeconds', 'fadeOutSeconds', 'dialoguePolicy', 'visualCompanion'], properties: { id: { type: 'string' }, startSeconds: { type: 'number' }, endSeconds: { type: 'number' }, type: { type: 'string', enum: ['music', 'laugh_track', 'pop', 'sting', 'silence'] }, purpose: { type: 'string' }, mood: { type: 'string' }, energy: { type: 'number', minimum: 0, maximum: 1 }, gainDb: { type: 'number', minimum: -96, maximum: 0 }, fadeInSeconds: { type: 'number', minimum: 0, maximum: 10 }, fadeOutSeconds: { type: 'number', minimum: 0, maximum: 10 }, dialoguePolicy: { type: 'string', enum: ['no_dialogue', 'duck_under_dialogue', 'replace_source_audio'] }, visualCompanion: { type: 'string' } } };
const analysisJsonSchema = { type: 'object', additionalProperties: false, required: ['projectId', 'durationSeconds', 'scenes', 'soundtrackBrief', 'soundtrackSegments', 'audioCues', 'editingSignals', 'viewerScore'], properties: { projectId: { type: 'string' }, durationSeconds: { type: 'number' }, scenes: { type: 'array', minItems: 1, items: { type: 'object', additionalProperties: false, required: ['id', 'startSeconds', 'endSeconds', 'summary', 'transcript', 'mood', 'energy', 'pacingFlags'], properties: { id: { type: 'string' }, startSeconds: { type: 'number' }, endSeconds: { type: 'number' }, summary: { type: 'string' }, transcript: { type: 'string' }, mood: { type: 'string' }, energy: { type: 'number', minimum: 0, maximum: 1 }, pacingFlags: { type: 'array', items: { type: 'string' } } } } }, soundtrackBrief: { type: 'object', additionalProperties: false, required: ['mood', 'tempo', 'instrumentation', 'prompt'], properties: { mood: { type: 'string' }, tempo: { type: 'string' }, instrumentation: { type: 'string' }, prompt: { type: 'string' } } }, soundtrackSegments: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['id', 'startSeconds', 'endSeconds', 'mood', 'energy', 'label'], properties: { id: { type: 'string' }, startSeconds: { type: 'number' }, endSeconds: { type: 'number' }, mood: { type: 'string' }, energy: { type: 'number', minimum: 0, maximum: 1 }, label: { type: 'string' } } } }, audioCues: { type: 'array', items: cueJsonSchema }, editingSignals: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['id', 'startSeconds', 'endSeconds', 'type', 'confidence', 'detail', 'suggestedAction'], properties: { id: { type: 'string' }, startSeconds: { type: 'number' }, endSeconds: { type: 'number' }, type: { type: 'string', enum: ['silence', 'repetition', 'tangent', 'setup', 'low_information_action', 'emphasis', 'visual_issue', 'audio_noise', 'overlay_opportunity', 'joke', 'reveal', 'momentum_shift', 'montage'] }, confidence: { type: 'number', minimum: 0, maximum: 1 }, detail: { type: 'string' }, suggestedAction: { type: 'string' } } } }, viewerScore: scoreJsonSchema } };
