import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { recommendationSchema, type Recommendation } from '@dailies/shared';

export function buildCorrelationQuery(ownerId: string, duration: number) {
  const owner = ownerId.replaceAll("'", "''");
  return `WITH recent AS (SELECT video_id, title, duration_seconds FROM videos WHERE channel_id = '${owner}' ORDER BY published_at DESC LIMIT 5), drops AS (SELECT r.video_id, r.position_ratio, r.audience_watch_ratio, lagInFrame(r.audience_watch_ratio, 1, r.audience_watch_ratio) OVER (PARTITION BY r.video_id ORDER BY r.position_ratio) - r.audience_watch_ratio AS drop_ratio FROM retention_curve_points r INNER JOIN recent v USING (video_id)), ranked AS (SELECT round(position_ratio, 2) position_ratio, avg(drop_ratio) severity, groupUniqArray(video_id) supporting_video_ids FROM drops GROUP BY position_ratio HAVING length(supporting_video_ids) >= 2 ORDER BY severity DESC LIMIT 1) SELECT ranked.position_ratio, ranked.position_ratio * ${duration} target_seconds, ranked.severity * 100 severity_percent, ranked.supporting_video_ids, v.video_id, v.title, v.duration_seconds, ranked.position_ratio * v.duration_seconds position_seconds, groupUniqArrayIf(e.event_type, abs(e.position_ratio - ranked.position_ratio) <= .03) nearby_events FROM ranked ARRAY JOIN ranked.supporting_video_ids sid INNER JOIN recent v ON v.video_id = sid LEFT JOIN cut_events e ON e.video_id = v.video_id GROUP BY ranked.position_ratio, target_seconds, severity_percent, ranked.supporting_video_ids, v.video_id, v.title, v.duration_seconds, position_seconds`;
}
export async function queryRetention(ownerId: string, duration: number): Promise<Recommendation> {
  const url = required('CLICKHOUSE_MCP_URL'); const client = new Client({ name: 'dailies-retention-agent', version: '0.1.0' }); const transport = new StreamableHTTPClientTransport(new URL(url), process.env.CLICKHOUSE_MCP_AUTH_TOKEN ? { requestInit: { headers: { authorization: `Bearer ${process.env.CLICKHOUSE_MCP_AUTH_TOKEN}` } } } : undefined);
  try { await client.connect(transport); const result: any = await client.callTool({ name: 'run_query', arguments: { query: buildCorrelationQuery(ownerId, duration) } }); if (result.isError) throw new Error('ClickHouse MCP query failed'); const text = result.content?.filter((item: any) => item.type === 'text').map((item: any) => item.text).join('') || '[]'; return recommendationFromRows(JSON.parse(text)); } finally { await client.close(); }
}
export function recommendationFromRows(rows: any[]): Recommendation {
  if (!rows.length) throw new Error('ClickHouse MCP returned no repeated retention pattern'); const first = rows[0]; const ratio = Number(first.position_ratio); const severity = Math.max(0, Number(first.severity_percent)); const supporting = first.supporting_video_ids || [];
  const evidence = rows.map((row) => ({ videoId: String(row.video_id), title: String(row.title), durationSeconds: Number(row.duration_seconds), positionRatio: ratio, positionSeconds: Number(row.position_seconds), dropPercent: severity, nearbyEvents: row.nearby_events || [] })); const events = [...new Set(evidence.flatMap((item) => item.nearbyEvents))];
  return recommendationSchema.parse({ dropOffPositionRatio: ratio, dropOffSeconds: Number(first.target_seconds), severityPercent: severity, observedEvidence: `${supporting.length} recent videos share a local retention decline near ${Math.round(ratio * 100)}% of runtime${events.length ? `, with nearby events: ${events.join(', ')}.` : '. No nearby edit/music events were available.'}`, inferredCause: events.length ? 'A nearby edit or music transition may contribute to the repeated decline; this is correlation, not causal proof.' : 'The cause cannot be inferred without nearby edit or music event data.', recommendationText: `Review the transition around ${Number(first.target_seconds).toFixed(1)}s and preserve momentum through that window.`, suggestedAction: 'Test one version with continuous score and a tighter visual transition, then compare retention after publishing.', confidence: supporting.length >= 3 ? 'moderate' : 'emerging', supportingVideoIds: supporting, evidence });
}
const required = (name: string) => { const value = process.env[name]; if (!value) throw new Error(`${name} is required`); return value; };
