import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { recommendationSchema, type Recommendation } from '@dailies/shared';

export function buildCorrelationQuery(ownerId: string, duration: number) {
  const owner = ownerId.replaceAll("'", "''");
  return `WITH recent AS (SELECT video_id, title, duration_seconds FROM videos WHERE channel_id = '${owner}' ORDER BY published_at DESC LIMIT 5), drops AS (SELECT r.video_id, r.position_ratio, r.audience_watch_ratio, lagInFrame(r.audience_watch_ratio, 1, r.audience_watch_ratio) OVER (PARTITION BY r.video_id ORDER BY r.position_ratio) - r.audience_watch_ratio AS drop_ratio FROM retention_curve_points r INNER JOIN recent v USING (video_id)), ranked AS (SELECT round(position_ratio, 2) position_ratio, avg(drop_ratio) severity, groupUniqArray(video_id) supporting_video_ids FROM drops GROUP BY position_ratio HAVING length(supporting_video_ids) >= 2 ORDER BY severity DESC LIMIT 1), expanded AS (SELECT position_ratio, severity, supporting_video_ids, arrayJoin(supporting_video_ids) AS video_id FROM ranked) SELECT expanded.position_ratio AS position_ratio, expanded.position_ratio * ${duration} AS target_seconds, expanded.severity * 100 AS severity_percent, expanded.supporting_video_ids AS supporting_video_ids, v.video_id AS video_id, v.title AS title, v.duration_seconds AS duration_seconds, expanded.position_ratio * v.duration_seconds AS position_seconds, groupUniqArrayIf(e.event_type, abs(e.position_ratio - expanded.position_ratio) <= .03) AS nearby_events FROM expanded INNER JOIN recent v USING (video_id) LEFT JOIN cut_events e ON e.video_id = v.video_id GROUP BY position_ratio, target_seconds, severity_percent, supporting_video_ids, video_id, title, duration_seconds, position_seconds`;
}
export async function queryRetention(ownerId: string, duration: number): Promise<Recommendation> {
  const url = process.env.CLICKHOUSE_MCP_URL; if (!url) return recommendationFromRows([], duration);
  const client = new Client({ name: 'dailies-retention-agent', version: '0.1.0' }); const transport = new StreamableHTTPClientTransport(new URL(url), process.env.CLICKHOUSE_MCP_AUTH_TOKEN ? { requestInit: { headers: { authorization: `Bearer ${process.env.CLICKHOUSE_MCP_AUTH_TOKEN}` } } } : undefined);
  try { await client.connect(transport); const result: any = await client.callTool({ name: 'run_query', arguments: { query: buildCorrelationQuery(ownerId, duration) } }); const text = result.content?.filter((item: any) => item.type === 'text').map((item: any) => item.text).join('') || '[]'; if (result.isError) throw new Error('ClickHouse MCP query failed'); return recommendationFromRows(rowsFromMcpText(text), duration); } catch (error: any) { console.warn(JSON.stringify({ level: 'warn', event: 'retention_history_unavailable', message: String(error?.message || error).slice(0, 200) })); return recommendationFromRows([], duration); } finally { await client.close().catch(() => undefined); }
}
export function rowsFromMcpText(text: string): any[] { const parsed = JSON.parse(text); if (Array.isArray(parsed)) return parsed; if (Array.isArray(parsed?.rows)) { if (Array.isArray(parsed.columns) && parsed.rows.some((row: unknown) => Array.isArray(row))) return parsed.rows.map((row: unknown[]) => Object.fromEntries(parsed.columns.map((column: string | { name?: string }, index: number) => [typeof column === 'string' ? column : column.name || String(index), row[index]]))); return parsed.rows; } if (Array.isArray(parsed?.data)) return parsed.data; throw new Error('ClickHouse MCP returned an unsupported result shape'); }
export function recommendationFromRows(rows: any[], duration = 0): Recommendation {
  if (!rows.length) return recommendationSchema.parse({ dropOffPositionRatio: 0, dropOffSeconds: 0, severityPercent: 0, observedEvidence: 'No synchronized YouTube retention history is available for this creator.', inferredCause: 'Historical retention cannot be inferred without at least two authorized creator videos.', recommendationText: 'Use the uploaded cut\'s analysis as the editing baseline; YouTube history is optional.', suggestedAction: 'Optionally connect YouTube to add historical retention evidence to a future pass.', confidence: 'emerging', supportingVideoIds: [], evidence: [], retentionCurve: duration ? [{ positionRatio: 0, audienceWatchRatio: 1 }] : undefined }); const first = rows[0]; const ratio = Number(first.position_ratio); const severity = Math.max(0, Number(first.severity_percent)); const supporting = first.supporting_video_ids || [];
  const evidence = rows.map((row) => ({ videoId: String(row.video_id), title: String(row.title), durationSeconds: Number(row.duration_seconds), positionRatio: ratio, positionSeconds: Number(row.position_seconds), dropPercent: severity, nearbyEvents: row.nearby_events || [] })); const events = [...new Set(evidence.flatMap((item) => item.nearbyEvents))];
  return recommendationSchema.parse({ dropOffPositionRatio: ratio, dropOffSeconds: Number(first.target_seconds), severityPercent: severity, observedEvidence: `${supporting.length} recent videos share a local retention decline near ${Math.round(ratio * 100)}% of runtime${events.length ? `, with nearby events: ${events.join(', ')}.` : '. No nearby edit/music events were available.'}`, inferredCause: events.length ? 'A nearby edit or music transition may contribute to the repeated decline; this is correlation, not causal proof.' : 'The cause cannot be inferred without nearby edit or music event data.', recommendationText: `Review the transition around ${Number(first.target_seconds).toFixed(1)}s and preserve momentum through that window.`, suggestedAction: 'Test a tighter transition or cue-specific audio only where the current-cut analysis supports it, then compare retention after publishing.', confidence: supporting.length >= 3 ? 'moderate' : 'emerging', supportingVideoIds: supporting, evidence });
}
