import { GoogleGenAI } from '@google/genai';
import { editorialReviewSchema, type AnalysisResult, type EditPlan, type EditorialReview, type Recommendation } from '@dailies/shared';

export async function reviewRenderedDraft(input: { iteration: number; sourceUri: string; sourceMimeType: string; draftUri: string; analysis: AnalysisResult; editPlan: EditPlan; recommendation: Recommendation }): Promise<EditorialReview> {
  const ai = new GoogleGenAI({ vertexai: true, project: required('GCP_PROJECT_ID'), location: process.env.VERTEX_LOCATION || 'global' });
  const prompt = `You are the senior finishing editor for Dailies. Watch both the creator's original rough assembly and rendered draft iteration ${input.iteration}. Do not approve merely because the draft rendered successfully.
Evaluate whether the draft materially improves viewer value per second while preserving meaning and personality. There is no required compression ratio. Decide from the footage: flag repeated explanations, mildly unrelated tangents, coughs, sniffles, stutters, false starts, slow setup, routine handling, and long dead pauses when they can be removed without harming the central story; never penalize valuable footage merely because the final cut remains long. Inspect the opening hook, jump-cut timing, dead air, reveal emphasis, sticker/effect synchronization, full-frame intro/outro treatment, dialogue continuity, white-noise cleanup, source/music transitions, color consistency, and final payoff. Music must be selective. During retained dialogue the original narration must remain natural and full-level; source audio may be muted only for an intentional music-led intro, outro, montage, or fast-forward interval. Visual effects must be earned, context-specific, readable, and paired with appropriate sound when present.
Original diagnosis: ${JSON.stringify(input.analysis)}
For accelerated process footage, verify that the action still reads clearly, meaningful before/result anchor beats survive, and the chosen rate is the slowest one that keeps the passage engaging. A music-only, single-setting passage with little visual change should normally resolve in about 5-10 seconds; flag a 30-second stretch that merely repeats the same view or action. Permit a longer passage when it contains distinct visual beats, meaningful scenery changes, and a clear setup-to-result mini-arc that keeps rewarding attention. Flag needless 100x treatment when 10x or another lower rate would preserve more satisfying motion. The speed must be earned rather than hiding disposable footage or racing through instruction; original source audio must be completely absent, scene-specific music must support only the montage, and the cut must return cleanly to full-level normal dialogue. Treat process as core content in tutorials and how-it-is-made videos; do not demand extreme speed merely because the action is lengthy.
Creator evidence: ${JSON.stringify(input.recommendation)}
Executed edit plan: ${JSON.stringify(input.editPlan)}
Return a strict review. decision=pass only when there are no blocking issues and no major issue that would materially improve the viewer experience. Otherwise decision=revise and provide timestamped, executable required changes. Score the rendered draft itself, not the plan.`;
  const response = await ai.models.generateContent({ model: process.env.GEMINI_REVIEW_MODEL || process.env.GEMINI_MODEL || 'gemini-3-flash-preview', contents: [{ role: 'user', parts: [{ fileData: { fileUri: input.sourceUri, mimeType: input.sourceMimeType } }, { fileData: { fileUri: input.draftUri, mimeType: 'video/mp4' } }, { text: prompt }] }], config: { responseMimeType: 'application/json', responseJsonSchema: reviewJsonSchema } });
  if (!response.text) throw new Error('Gemini editorial reviewer returned no structured review');
  return editorialReviewSchema.parse({ ...JSON.parse(response.text), iteration: input.iteration });
}

const issueJsonSchema = { type: 'object', additionalProperties: false, required: ['category', 'startSeconds', 'endSeconds', 'severity', 'diagnosis', 'requiredChange'], properties: { category: { type: 'string', enum: ['hook', 'pacing', 'clarity', 'visual', 'audio', 'continuity', 'ending'] }, startSeconds: { type: 'number', minimum: 0 }, endSeconds: { type: 'number', exclusiveMinimum: 0 }, severity: { type: 'string', enum: ['minor', 'major', 'blocking'] }, diagnosis: { type: 'string' }, requiredChange: { type: 'string' } } };
const scoreJsonSchema = { type: 'object', additionalProperties: false, required: ['hook', 'pacing', 'clarity', 'visualQuality', 'audioQuality', 'total', 'rationale'], properties: { hook: { type: 'number', minimum: 0, maximum: 100 }, pacing: { type: 'number', minimum: 0, maximum: 100 }, clarity: { type: 'number', minimum: 0, maximum: 100 }, visualQuality: { type: 'number', minimum: 0, maximum: 100 }, audioQuality: { type: 'number', minimum: 0, maximum: 100 }, total: { type: 'number', minimum: 0, maximum: 100 }, rationale: { type: 'string' } } };
const reviewJsonSchema = { type: 'object', additionalProperties: false, required: ['iteration', 'decision', 'score', 'summary', 'issues'], properties: { iteration: { type: 'number', minimum: 1 }, decision: { type: 'string', enum: ['pass', 'revise'] }, score: scoreJsonSchema, summary: { type: 'string' }, issues: { type: 'array', items: issueJsonSchema } } };
const required = (name: string) => { const value = process.env[name]; if (!value) throw new Error(`${name} is required`); return value; };
