import { google } from 'googleapis'; import { parse, toSeconds } from 'iso8601-duration';
export type OAuthCredentials = { access_token?: string | null; refresh_token?: string | null; expiry_date?: number | null; token_type?: string | null; scope?: string };
export type RetentionPoint = { video_id: string; position_ratio: number; position_seconds: number; audience_watch_ratio: number };
export function normalizeRetention(videoId: string, duration: number, rows: unknown[][]): RetentionPoint[] { return rows.map(([ratio, watch]) => { const position = Number(ratio); if (position < 0 || position > 1) throw new Error('YouTube returned an invalid normalized position'); return { video_id: videoId, position_ratio: position, position_seconds: position * duration, audience_watch_ratio: Number(watch) }; }); }
export function oauthClient(credentials: OAuthCredentials) { const client = new google.auth.OAuth2(required('YOUTUBE_OAUTH_CLIENT_ID'), required('YOUTUBE_OAUTH_CLIENT_SECRET'), required('YOUTUBE_OAUTH_REDIRECT_URI')); client.setCredentials(credentials); return client; }
export async function readCreatorRetention(credentials: OAuthCredentials, onProgress: (message: string) => void = () => undefined) {
  const auth = oauthClient(credentials); const youtube = google.youtube({ version: 'v3', auth }); const analytics = google.youtubeAnalytics({ version: 'v2', auth });
  const channelResponse = await youtube.channels.list({ part: ['id', 'contentDetails'], mine: true }); const channels = channelResponse.data.items || []; if (channels.length !== 1) throw new Error('Expected one authorized creator channel');
  const channel = channels[0]; const channelId = channel.id!; const playlistId = channel.contentDetails?.relatedPlaylists?.uploads; if (!playlistId) throw new Error('Authorized channel has no uploads playlist'); onProgress('Authorized YouTube channel confirmed.');
  const playlist = await youtube.playlistItems.list({ part: ['contentDetails'], playlistId, maxResults: Math.min(50, Number(process.env.YOUTUBE_VIDEO_LIMIT || 10)) }); const ids = (playlist.data.items || []).map((item) => item.contentDetails?.videoId).filter((id): id is string => Boolean(id));
  onProgress(`Found ${ids.length} recent channel video${ids.length === 1 ? '' : 's'} to inspect.`);
  if (!ids.length) return { channelId, videos: [] };
  const metadata = await youtube.videos.list({ part: ['snippet', 'contentDetails'], id: ids }); const videos = [];
  const items = metadata.data.items || []; let current = 0;
  for (const video of items) { if (!video.id || !video.contentDetails?.duration) continue; current += 1; onProgress(`Requesting retention report ${current} of ${items.length}.`); const durationSeconds = toSeconds(parse(video.contentDetails.duration)); const report = await analytics.reports.query({ ids: 'channel==MINE', startDate: process.env.YOUTUBE_START_DATE || '2006-01-01', endDate: new Date().toISOString().slice(0, 10), metrics: 'audienceWatchRatio', dimensions: 'elapsedVideoTimeRatio', filters: `video==${video.id}`, sort: 'elapsedVideoTimeRatio' }); const points = normalizeRetention(video.id, durationSeconds, (report.data.rows || []) as unknown[][]); videos.push({ video: { video_id: video.id, channel_id: channelId, title: video.snippet?.title || video.id, published_at: video.snippet?.publishedAt || new Date(0).toISOString(), duration_seconds: Math.round(durationSeconds) }, points }); onProgress(`Retention report ${current} of ${items.length} received (${points.length} points).`); }
  return { channelId, videos };
}
const required = (name: string) => { const value = process.env[name]; if (!value) throw new Error(`${name} is required`); return value; };
