import React, { useEffect, useRef } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import AppShell from './components/AppShell'; import AuthPage from './components/AuthPage'; import Dashboard from './components/Dashboard'; import ProjectUploader from './components/ProjectUploader'; import WorkflowStepper from './components/WorkflowStepper'; import ErrorState from './components/ErrorState'; import VideoPreview from './components/VideoPreview'; import AnalysisPanel from './components/AnalysisPanel'; import SoundtrackCard from './components/SoundtrackCard'; import RetentionChart from './components/RetentionChart'; import EvidencePanel from './components/EvidencePanel'; import RecommendationCard from './components/RecommendationCard'; import EditPlan from './components/EditPlan'; import FinalCutPlayer from './components/FinalCutPlayer';
import { activeStepChanged, analysisReset, analysisSceneSelected, evidenceToggled, fetchProject, insightReset, loadSession, openProject, projectReset, retryProject, submitProject, uiReset, viewChanged } from './store';

export default function App() {
  const dispatch = useDispatch(); const project = useSelector((s) => s.project); const analysis = useSelector((s) => s.analysis); const insight = useSelector((s) => s.insight); const ui = useSelector((s) => s.ui); const auth = useSelector((s) => s.auth); const mainRef = useRef(null);
  const selectedScene = analysis.result?.scenes.find((scene) => scene.id === analysis.selectedSceneId) || analysis.result?.scenes[0];
  useEffect(() => { dispatch(loadSession()); }, [dispatch]);
  useEffect(() => { if (!project.id || !['uploaded', 'analyzing', 'scoring', 'querying_insights', 'waiting_for_service', 'editing', 'rendering'].includes(project.status)) return undefined; const timer = window.setInterval(() => dispatch(fetchProject(project.id)), 2000); return () => window.clearInterval(timer); }, [dispatch, project.id, project.status]);
  useEffect(() => { if (project.status === 'complete') { dispatch(activeStepChanged('analysis')); mainRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }); } }, [dispatch, project.status]);
  const resetProject = () => { dispatch(projectReset()); dispatch(analysisReset()); dispatch(insightReset()); };
  const startNewProject = () => { window.scrollTo({ top: 0 }); resetProject(); dispatch(activeStepChanged('project')); dispatch(viewChanged('project')); };
  const showProject = async (id) => { await dispatch(openProject(id)); dispatch(viewChanged('project')); window.scrollTo({ top: 0 }); };
  const navigate = (destination) => { dispatch(viewChanged('dashboard')); window.setTimeout(() => destination === 'projects' ? document.querySelector('.project-library')?.scrollIntoView({ behavior: 'smooth' }) : destination === 'insights' ? document.querySelector('.dashboard-focus')?.scrollIntoView({ behavior: 'smooth' }) : window.scrollTo({ top: 0, behavior: 'smooth' }), 0); };
  const switchStep = (step) => { if (project.status !== 'complete' && step !== 'project') return; dispatch(activeStepChanged(step)); document.getElementById(step)?.scrollIntoView({ behavior: 'smooth' }); };
  if (auth.status === 'loading') return <main className="auth-page"><section className="auth-form-area"><div className="auth-card"><p className="eyebrow">Creator studio</p><h1>Opening your studio…</h1></div></section></main>;
  if (auth.status !== 'authenticated') return <AuthPage error={auth.error} onSubmit={() => window.location.assign(import.meta.env.VITE_GOOGLE_SIGN_IN_URL || window.location.href)} />;
  const fixtureMode = Boolean(auth.fixtureMode || project.fixtureMode);
  return <AppShell view={ui.view} activeStep={ui.activeStep} onNavigate={navigate} onStepChange={switchStep} onSignOut={() => window.location.assign(import.meta.env.VITE_SIGN_OUT_URL || '/')} user={auth.user}>
    {fixtureMode && <div className="fixture-caption centered" role="status"><strong>Offline fixture mode</strong> — data on this screen is not from live services.</div>}
    {ui.view === 'dashboard' && <Dashboard user={auth.user} projects={auth.projects} fixtureMode={fixtureMode} onNewProject={startNewProject} onOpenProject={showProject} onBrowseProjects={() => navigate('projects')} />}
    {ui.view === 'project' && <main ref={mainRef} className="studio-main">
      {project.status === 'idle' && <div id="project-form"><ProjectUploader onSubmit={(payload) => dispatch(submitProject(payload))} /></div>}
      {['uploading', 'created', 'uploaded', 'analyzing', 'scoring', 'querying_insights', 'waiting_for_service', 'editing', 'rendering'].includes(project.status) && <section className="processing-view"><div className="processing-copy"><p className="eyebrow">{project.status === 'uploaded' ? 'Project ready' : project.status === 'waiting_for_service' ? 'Pipeline checkpointed' : 'Project in progress'}</p><h1>Making sense of the <em>material.</em></h1><p>{project.status === 'uploading' ? 'Uploading your footage to its private project workspace.' : project.status === 'uploaded' ? 'Your cloud upload is safe and ready. Start the analysis and enhancement pipeline when you are ready.' : project.status === 'waiting_for_service' ? 'Analysis and soundtrack are safe. Processing will resume at Insight as soon as ClickHouse MCP is configured.' : 'Dailies is analyzing, scoring, editing, and rendering the enhanced cut.'}</p><p className="project-file">{project.fileName}</p>{project.status === 'uploaded' && <button className="button primary" onClick={() => dispatch(retryProject(project.id))}>Analyze and enhance</button>}</div><WorkflowStepper status={project.status} currentStage={project.processingStage} /></section>}
      {project.status === 'failed' && <ErrorState message={project.error} onRetry={() => project.id ? dispatch(retryProject(project.id)) : startNewProject()} onReset={startNewProject} />}
      {project.status === 'complete' && analysis.result && insight.result && <div className="project-report"><div className="report-intro"><div><p className="eyebrow">Project report {fixtureMode && <span className="demo-badge">Fixture data</span>}</p><h1>{project.fileName.replace(/\.[^/.]+$/, '')}</h1><p>One pass through a new cut, grounded in your creator data.</p></div><div className="project-metrics"><span><strong>{Math.round(analysis.result.durationSeconds)}s</strong> rough cut</span><span><strong>{analysis.result.scenes.length}</strong> scenes found</span><span><strong>{insight.result.supportingVideoIds.length}</strong> source videos</span></div></div>
        {project.report?.finalCut && <FinalCutPlayer projectId={project.id} finalCut={project.report.finalCut} />}
        <section id="analysis" className="preview-and-analysis"><VideoPreview projectId={project.id} assetId={project.uploadAssetId} scene={selectedScene} duration={analysis.result.durationSeconds} /><AnalysisPanel fixtureMode={fixtureMode} result={analysis.result} selectedScene={selectedScene} selectedSceneId={analysis.selectedSceneId} onSceneSelect={(id) => dispatch(analysisSceneSelected(id))} /></section>
        <section id="score"><SoundtrackCard projectId={project.id} soundtrack={project.report?.soundtrack} brief={analysis.result.soundtrackBrief} segments={analysis.result.soundtrackSegments} fixtureMode={fixtureMode} /></section>
        <section id="insight" className="insight-section"><div className="section-heading"><div><p className="eyebrow">03 · Retention insight</p><h2>A pattern worth holding onto.</h2></div>{fixtureMode && <span className="demo-badge">Fixture evidence</span>}</div><RetentionChart insight={insight.result} /><EvidencePanel insight={insight.result} fixtureMode={fixtureMode} open={ui.evidenceOpen} onToggle={() => dispatch(evidenceToggled())} /></section><RecommendationCard insight={insight.result} /><EditPlan plan={project.report?.editPlan} /><div className="new-project"><span>Ready for another pass?</span><button className="button secondary" onClick={startNewProject}>Start a new project</button></div></div>}
    </main>}
  </AppShell>;
}
